# Generated by Django 3.2.4 on 2021-06-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
