# Generated by Django 3.2.4 on 2021-06-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
