# Generated by Django 3.2.4 on 2021-06-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.URLField(max_length=255),
        ),
    ]
