# Generated by Django 3.2.4 on 2021-06-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_album_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='personnel',
        ),
    ]
